service: stockspulse
frameworkVersion: "3"

useDotenv: true

provider: 
  name: yandex-cloud 
  runtime: nodejs16 
  httpApi: 
    payload: '1.0' 
  
functions: 
  gql:
    environment:
      GRAPHQL_ENDPOINT: ${env:GRAPHQL_ENDPOINT}
    handler: dist/index.graphqlHandler 
    memorySize: 256 
    timeout: 60

plugins: 
  - "@yandex-cloud/serverless-plugin"
  - "serverless-dotenv-plugin"
  
package: 
  patterns: 
  - '!**' 
  - package.json 
  - package-lock.json 
  - dist/**/*.js
 